# Generated by Django 3.2.8 on 2021-10-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeshort', '0004_alter_shorturl_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
